const champions = [
    // Bandle City
    { name: "Corki", origin: "Bandle City", id: "Corki" },
    { name: "Fizz", origin: "Bandle City", id: "Fizz" },
    { name: "Gnar", origin: "Bandle City", id: "Gnar" },
    { name: "Heimerdinger", origin: "Bandle City", id: "Heimerdinger" },
    { name: "Kennen", origin: "Bandle City", id: "Kennen" },
    { name: "Kled", origin: "Bandle City", id: "Kled" },
    { name: "Lulu", origin: "Bandle City", id: "Lulu" },
    { name: "Poppy", origin: "Bandle City", id: "Poppy" },
    { name: "Rumble", origin: "Bandle City", id: "Rumble" },
    { name: "Teemo", origin: "Bandle City", id: "Teemo" },
    { name: "Tristana", origin: "Bandle City", id: "Tristana" },
    { name: "Veigar", origin: "Bandle City", id: "Veigar" },
    { name: "Vex", origin: "Bandle City", id: "Vex" },
    { name: "Yuumi", origin: "Bandle City", id: "Yuumi" },
    { name: "Ziggs", origin: "Bandle City", id: "Ziggs" },

    // Bilgewater
    { name: "Fizz", origin: "Bilgewater", id: "Fizz" },
    { name: "Gangplank", origin: "Bilgewater", id: "Gangplank" },
    { name: "Graves", origin: "Bilgewater", id: "Graves" },
    { name: "Illaoi", origin: "Bilgewater", id: "Illaoi" },
    { name: "Miss Fortune", origin: "Bilgewater", id: "MissFortune" },
    { name: "Nautilus", origin: "Bilgewater", id: "Nautilus" },
    { name: "Nilah", origin: "Bilgewater", id: "Nilah" },
    { name: "Pyke", origin: "Bilgewater", id: "Pyke" },
    { name: "Tahm Kench", origin: "Bilgewater", id: "TahmKench" },
    { name: "Twisted Fate", origin: "Bilgewater", id: "TwistedFate" },

    // Demacia
    { name: "Fiora", origin: "Demacia", id: "Fiora" },
    { name: "Galio", origin: "Demacia", id: "Galio" },
    { name: "Garen", origin: "Demacia", id: "Garen" },
    { name: "Jarvan IV", origin: "Demacia", id: "JarvanIV" },
    { name: "Kayle", origin: "Demacia", id: "Kayle" },
    { name: "Lucian", origin: "Demacia", id: "Lucian" },
    { name: "Lux", origin: "Demacia", id: "Lux" },
    { name: "Morgana", origin: "Demacia", id: "Morgana" },
    { name: "Poppy", origin: "Demacia", id: "Poppy" },
    { name: "Quinn", origin: "Demacia", id: "Quinn" },
    { name: "Shyvana", origin: "Demacia", id: "Shyvana" },
    { name: "Sona", origin: "Demacia", id: "Sona" },
    { name: "Sylas", origin: "Demacia", id: "Sylas" },
    { name: "Vayne", origin: "Demacia", id: "Vayne" },
    { name: "Xin Zhao", origin: "Demacia", id: "XinZhao" },

    // Freljord
    { name: "Anivia", origin: "Freljord", id: "Anivia" },
    { name: "Ashe", origin: "Freljord", id: "Ashe" },
    { name: "Aurora", origin: "Freljord", id: "Aurora" },
    { name: "Braum", origin: "Freljord", id: "Braum" },
    { name: "Gnar", origin: "Freljord", id: "Gnar" },
    { name: "Gragas", origin: "Freljord", id: "Gragas" },
    { name: "Lissandra", origin: "Freljord", id: "Lissandra" },
    { name: "Nunu & Willump", origin: "Freljord", id: "Nunu" },
    { name: "Olaf", origin: "Freljord", id: "Olaf" },
    { name: "Ornn", origin: "Freljord", id: "Ornn" },
    { name: "Sejuani", origin: "Freljord", id: "Sejuani" },
    { name: "Trundle", origin: "Freljord", id: "Trundle" },
    { name: "Tryndamere", origin: "Freljord", id: "Tryndamere" },
    { name: "Udyr", origin: "Freljord", id: "Udyr" },
    { name: "Volibear", origin: "Freljord", id: "Volibear" },

    // Ionia
    { name: "Ahri", origin: "Ionia", id: "Ahri" },
    { name: "Akali", origin: "Ionia", id: "Akali" },
    { name: "Hwei", origin: "Ionia", id: "Hwei" },
    { name: "Irelia", origin: "Ionia", id: "Irelia" },
    { name: "Ivern", origin: "Ionia", id: "Ivern" },
    { name: "Jhin", origin: "Ionia", id: "Jhin" },
    { name: "Karma", origin: "Ionia", id: "Karma" },
    { name: "Kayn", origin: "Ionia", id: "Kayn" },
    { name: "Kennen", origin: "Ionia", id: "Kennen" },
    { name: "Lee Sin", origin: "Ionia", id: "LeeSin" },
    { name: "Lillia", origin: "Ionia", id: "Lillia" },
    { name: "Master Yi", origin: "Ionia", id: "MasterYi" },
    { name: "Rakan", origin: "Ionia", id: "Rakan" },
    { name: "Sett", origin: "Ionia", id: "Sett" },
    { name: "Shen", origin: "Ionia", id: "Shen" },
    { name: "Syndra", origin: "Ionia", id: "Syndra" },
    { name: "Varus", origin: "Ionia", id: "Varus" },
    { name: "Wukong", origin: "Ionia", id: "MonkeyKing" },
    { name: "Xayah", origin: "Ionia", id: "Xayah" },
    { name: "Yasuo", origin: "Ionia", id: "Yasuo" },
    { name: "Yone", origin: "Ionia", id: "Yone" },
    { name: "Yunara", origin: "Ionia", id: "Yunara" },
    { name: "Zed", origin: "Ionia", id: "Zed" },

    // Ixtal
    { name: "Malphite", origin: "Ixtal", id: "Malphite" },
    { name: "Milio", origin: "Ixtal", id: "Milio" },
    { name: "Neeko", origin: "Ixtal", id: "Neeko" },
    { name: "Nidalee", origin: "Ixtal", id: "Nidalee" },
    { name: "Qiyana", origin: "Ixtal", id: "Qiyana" },
    { name: "Rengar", origin: "Ixtal", id: "Rengar" },
    { name: "Skarner", origin: "Ixtal", id: "Skarner" },
    { name: "Zyra", origin: "Ixtal", id: "Zyra" },

    // Noxus
    { name: "Ambessa", origin: "Noxus", id: "Ambessa" },
    { name: "Briar", origin: "Noxus", id: "Briar" },
    { name: "Cassiopeia", origin: "Noxus", id: "Cassiopeia" },
    { name: "Darius", origin: "Noxus", id: "Darius" },
    { name: "Draven", origin: "Noxus", id: "Draven" },
    { name: "Katarina", origin: "Noxus", id: "Katarina" },
    { name: "Kled", origin: "Noxus", id: "Kled" },
    { name: "LeBlanc", origin: "Noxus", id: "Leblanc" },
    { name: "Mel", origin: "Noxus", id: "Mel" },
    { name: "Mordekaiser", origin: "Noxus", id: "Mordekaiser" },
    { name: "Rell", origin: "Noxus", id: "Rell" },
    { name: "Riven", origin: "Noxus", id: "Riven" },
    { name: "Samira", origin: "Noxus", id: "Samira" },
    { name: "Sion", origin: "Noxus", id: "Sion" },
    { name: "Swain", origin: "Noxus", id: "Swain" },
    { name: "Talon", origin: "Noxus", id: "Talon" },
    { name: "Vladimir", origin: "Noxus", id: "Vladimir" },

    // Piltover
    { name: "Caitlyn", origin: "Piltover", id: "Caitlyn" },
    { name: "Camille", origin: "Piltover", id: "Camille" },
    { name: "Corki", origin: "Piltover", id: "Corki" },
    { name: "Ezreal", origin: "Piltover", id: "Ezreal" },
    { name: "Heimerdinger", origin: "Piltover", id: "Heimerdinger" },
    { name: "Jayce", origin: "Piltover", id: "Jayce" },
    { name: "Orianna", origin: "Piltover", id: "Orianna" },
    { name: "Seraphine", origin: "Piltover", id: "Seraphine" },
    { name: "Vi", origin: "Piltover", id: "Vi" },

    // Îles Obscures
    { name: "Elise", origin: "Îles Obscures", id: "Elise" },
    { name: "Fiddlesticks", origin: "Îles Obscures", id: "Fiddlesticks" },
    { name: "Gwen", origin: "Îles Obscures", id: "Gwen" },
    { name: "Hecarim", origin: "Îles Obscures", id: "Hecarim" },
    { name: "Kalista", origin: "Îles Obscures", id: "Kalista" },
    { name: "Karthus", origin: "Îles Obscures", id: "Karthus" },
    { name: "Maokai", origin: "Îles Obscures", id: "Maokai" },
    { name: "Senna", origin: "Îles Obscures", id: "Senna" },
    { name: "Thresh", origin: "Îles Obscures", id: "Thresh" },
    { name: "Vex", origin: "Îles Obscures", id: "Vex" },
    { name: "Viego", origin: "Îles Obscures", id: "Viego" },
    { name: "Yorick", origin: "Îles Obscures", id: "Yorick" },

    // Shurima
    { name: "Akshan", origin: "Shurima", id: "Akshan" },
    { name: "Amumu", origin: "Shurima", id: "Amumu" },
    { name: "Azir", origin: "Shurima", id: "Azir" },
    { name: "K'Sante", origin: "Shurima", id: "KSante" },
    { name: "Naafiri", origin: "Shurima", id: "Naafiri" },
    { name: "Nasus", origin: "Shurima", id: "Nasus" },
    { name: "Rammus", origin: "Shurima", id: "Rammus" },
    { name: "Renekton", origin: "Shurima", id: "Renekton" },
    { name: "Sivir", origin: "Shurima", id: "Sivir" },
    { name: "Taliyah", origin: "Shurima", id: "Taliyah" },
    { name: "Xerath", origin: "Shurima", id: "Xerath" },

    // Targon
    { name: "Aphelios", origin: "Targon", id: "Aphelios" },
    { name: "Aurelion Sol", origin: "Targon", id: "AurelionSol" },
    { name: "Diana", origin: "Targon", id: "Diana" },
    { name: "Leona", origin: "Targon", id: "Leona" },
    { name: "Pantheon", origin: "Targon", id: "Pantheon" },
    { name: "Soraka", origin: "Targon", id: "Soraka" },
    { name: "Taric", origin: "Targon", id: "Taric" },
    { name: "Zoe", origin: "Targon", id: "Zoe" },

    // Néant
    { name: "Bel'Veth", origin: "Néant", id: "Belveth" },
    { name: "Cho'Gath", origin: "Néant", id: "Chogath" },
    { name: "Kai'Sa", origin: "Néant", id: "Kaisa" },
    { name: "Khassadin", origin: "Néant", id: "Kassadin" },
    { name: "Kha'Zix", origin: "Néant", id: "Khazix" },
    { name: "Kog'Maw", origin: "Néant", id: "KogMaw" },
    { name: "Malzahar", origin: "Néant", id: "Malzahar" },
    { name: "Rek'Sai", origin: "Néant", id: "RekSai" },
    { name: "Vel'Koz", origin: "Néant", id: "Velkoz" },

    // Zaun
    { name: "Blitzcrank", origin: "Zaun", id: "Blitzcrank" },
    { name: "Dr. Mundo", origin: "Zaun", id: "DrMundo" },
    { name: "Ekko", origin: "Zaun", id: "Ekko" },
    { name: "Janna", origin: "Zaun", id: "Janna" },
    { name: "Jinx", origin: "Zaun", id: "Jinx" },
    { name: "Renata Glasc", origin: "Zaun", id: "Renata" },
    { name: "Singed", origin: "Zaun", id: "Singed" },
    { name: "Twitch", origin: "Zaun", id: "Twitch" },
    { name: "Urgot", origin: "Zaun", id: "Urgot" },
    { name: "Viktor", origin: "Zaun", id: "Viktor" },
    { name: "Warwick", origin: "Zaun", id: "Warwick" },
    { name: "Zac", origin: "Zaun", id: "Zac" },
    { name: "Zeri", origin: "Zaun", id: "Zeri" },
    { name: "Ziggs", origin: "Zaun", id: "Ziggs" },

];